### PR TITLE
[WIP] reproducible builds with docker

### PR DESCRIPTION
**Pull request by ocramz**
This PR adds docker support towards reproducible HMatrix builds and benchmarks. On the VM I'm currently usingg, building dependencies runs out of memory, but hopefully the VMs on Travis are larger.

* add development and deployment dockerfiles
* add `docker.enable` flag in stack file
* add makefile (shortcuts)
* add .travis.yml
* add `-f openblas` flag to benchmarks

### CODE REVIEW

**Comment by Magalame** [comment]
Thanks a lot for taking care of it!
I have a few questions:
- why go back to an earlier lts version in stack.yaml?
- I'm not sure exactly what does the `-f openblas` flag does
- if it runs out of memory on your VM, should we be worried about observing the same problem in a "normal" set-up?

**Comment by ocramz** [comment]
All good questions; there are a few intertwined issues here:

* I picked a base Alpine Linux since it's the smallest you can get, but unfortunately not all GHC versions are available for it because they have to be compiled ad hoc.
* regading the openblas flag: that's something I'm not sure about myself. I was hoping it would be passed to hmatrix (again, this is an Alpine limitation: only OpenBLAS is available for it)
* not sure about the memory error either; I got a `-9` exit error at Cabal build time, but maybe there's a way around it.

**Comment by ocramz** [comment]
First thing to try would be a different Linux distribution as base Docker image.

**Comment by Magalame** [comment]
Is it still in a WIP state?

**Comment by ocramz** [comment]
Yeah sorry, I've been really busy with work recently and couldn't give this proper attention. I'll try making some time for it in the next few days!

**Comment by Magalame** [comment]
No problem, sounds good!

**Comment by ocramz** [comment]
Closing for now, I've restarted it in my own fork using your latest changes: https://github.com/ocramz/fastest-matrices

**Comment by Magalame** [comment]
No problem!

**Pull request closed without merging**
